### ISSUE TITLE
Sync labels from Github

### ISSUE THREAD

**Issue by mattschrage** [jtormey/linear-sync#15]
Currently, Linear Sync imports the issue title and text, but does not sync Github labels with labels in Linear. 

I noticed in #14, sync is added in the reverse direction (Linear -> Github). It would be amazing if this worked in the other direction as well!

**Comment by jtormey** [comment]
Hey! This should sync both ways, however the for a label to be synced it must exist in both platforms. Matching is done by case-insensitive text comparison. Could you try adding the label that you want synced to Linear?

**Comment by mattschrage** [comment]
Ah amazing! I will test it out ASAP. Thanks so much @jtormey  :)

**Comment by mattschrage** [comment]
Hmm. I haven't been able to get this working.

<img width="1041" alt="Screen Shot 2021-07-09 at 10 18 54 PM" src="https://user-images.githubusercontent.com/3155109/125152758-aab3e580-e103-11eb-979e-7dc6467310c8.png">

I've been using [this issue](https://github.com/withfig/fig/issues/253) to test and I have double checked that the corresponding labels exist in Linear. 

<img width="378" alt="Screen Shot 2021-07-09 at 10 14 57 PM" src="https://user-images.githubusercontent.com/3155109/125152742-8eb04400-e103-11eb-8b6c-fe724c91becf.png">

It seems like the labels are identical. Is there anything else I should try?

**Comment by jtormey** [comment]
Good catch! Looks like there was an issue with comparing labels (Linear labels were being normalized, while Github labels were not, so the casing was causing your label changes to slip by).

This fix has been deployed, mind trying again?
