### ISSUE TITLE
Unable to fix "there is already an issue sync for this team repo combination"

### ISSUE THREAD

**Issue by mschrage** [jtormey/linear-sync#16]
Someone previously set up Linear Sync from an account that I no longer have access to. They have revoked authorization from their Github and their Linear account has been suspended. However, now, when I try to recreate the sync using my own Github account I receive the following error message: "there is already an issue sync for this team repo combination"

**Potential Solution**:
Other members of a Linear workspace should be able to remove pre-existing 'syncs'

**Comment by jtormey** [comment]
Yup, I've ran into this before. I'll see what can be done here.
