### ISSUE TITLE
One-way sync from Github to Linear

### ISSUE THREAD

**Issue by mschrage** [jtormey/linear-sync#18]
Previously, Linear Sync went one way - pulling issues from Github and adding them to Linear. It seems like two way sync is now the default. Is there a way to restore the previous behavior?

**Comment by jtormey** [comment]
Not at the moment, however I can see the use case. I will add an option for this.

In the meantime, note that any issues labeled as "private" will be kept in Linear only.

**Comment by mschrage** [comment]
Thanks so much @jtormey!

**Comment by mschrage** [comment]
If anyone else runs into this, you can create an issue template in Linear that automatically adds the `private` tag.
