### ISSUE TITLE
FUNDING.md does not work

### ISSUE THREAD

**Issue by underyx** [jtormey/linear-sync#21]
See screenshot of what pressing the Sponsor button shows:

<img width="514" alt="Screen Shot 2021-08-10 at 13 25 56" src="https://user-images.githubusercontent.com/1060436/128858948-7eb9695a-5ff2-488c-b87c-a56da58bc541.png">

**Comment by jtormey** [comment]
Thanks! My sponsorship application is under review, I'll post here when it's ready 🙂

**Comment by jtormey** [comment]
Should be all set now!
