### ISSUE TITLE
New issue in GitHub does not create new Linear issue

### ISSUE THREAD

**Issue by dudesahn** [jtormey/linear-sync#25]
**Expected Behavior** 
- New issues created in GitHub without a Linear issue ID in their name should create a new issue in Linear linked to the GitHub issue

**Current Behavior**
- Creating a new issue in GitHub that is not linked to an existing Linear issue does not create a new Linear issue.

**Comment by janbaykara** [comment]
I'm not able to reproduce this.

**Comment by jtormey** [comment]
This may be stale, closing unless someone is able to reproduce!
