### ISSUE TITLE
Any chance of reducing permissions?

### ISSUE THREAD

**Issue by leetrout** [jtormey/linear-sync#3]
This looks really great- is there any chance the integration permissions could be reduced and exclude code, deploy keys, etc?

**Comment by jtormey** [comment]
Thanks for the issue! A few questions:

* Which permissions do you mean? On the Linear or GitHub side?
* Where do you see deploy keys? Are you referring to the configured signing salts?
* What code should be excluded that isn't?

**Comment by leetrout** [comment]
Sorry for the delay- when connecting with linear-sync.com it's asking for a very broad set of read and write permissions. I'm not super familiar with the github scopes so I didn't know if there was a way to turn any of these settings down to only reading / writing issues.

![image](https://user-images.githubusercontent.com/524648/105125737-19947800-5aab-11eb-93d1-5bfa602ae4a3.png)

**Comment by jtormey** [comment]
Yes, ideally I would only request permission to read and write issues. However, it doesn't look like there's a GitHub scope that allows such fine grain permission.

See the scopes documentation: https://docs.github.com/en/developers/apps/scopes-for-oauth-apps

(This project uses the `"repo"` scope).

**Comment by jtormey** [comment]
@leetrout would you say this issue is still valid? Have you tried out the integration yet? Just checking in 🙂

**Comment by leetrout** [comment]
No, I can't try out the integration with access to everything like this. Wonder how linear itself is doing this and only requiring meta data and not code / etc access?

**Comment by jtormey** [comment]
It looks like [GitHub Apps](https://docs.github.com/en/rest/reference/permissions-required-for-github-apps) have more fine-tuned controls for permissions compared to OAuth Apps... which is what this project is. Something to look into.
