### ISSUE TITLE
Support two-way sync

### ISSUE THREAD

**Issue by jtormey** [jtormey/linear-sync#6]
Currently, this application only supports syncing new issues from GitHub to Linear. However, it would be nice if sync worked the other way as well.

Example use cases:

* When an issue is completed or archived in Linear, close the corresponding GitHub issue
* When an issue is commented on in Linear, add the comment to GitHub as well (maybe requiring some special syntax in the message, so that some comments may remain private)

For anyone looking to implement this feature, here are the relevant sections of the codebase:

* The code for setting up and tearing webhooks can be found in [Linear.IssueSyncService](https://github.com/jtormey/linear-sync/blob/ea075ba0189940a25a6c1efd72d83c1045f5216f/lib/linear/issue_sync_service.ex#L12-L61), and will simply need to be uncommented
* Creating webhooks is currently broken, due to changes in Linear's API. This will have to be fixed in [Linear.LinearAPI](https://github.com/jtormey/linear-sync/blob/ea075ba0189940a25a6c1efd72d83c1045f5216f/lib/linear/api/linear_api.ex) (and is the reason for the previously mentioned commented code)
* Incoming webhook requests from Linear will have to be handled and the "business logic" implemented, which is done in [Linear.Synchronize](https://github.com/jtormey/linear-sync/blob/ea075ba0189940a25a6c1efd72d83c1045f5216f/lib/linear/synchronize.ex)

**Comment by jtormey** [comment]
Thanks @seripap for fixing the webhook issue!

It looks like I get an error if I try to create more than one webhook for a team (makes sense). So, creating a new webhook for each `IssueSync` may have been misguided of me... I guess ideally the webhook would be created once, when the user signs in via API key.

Here is the relevant logging output:

```
17:28:11.739 [error] Failed to enable Linear webhook, {:ok, %{"data" => nil, "errors" => [%{"extensions" => %{"type" => "invalid input", "userError" => true, "userPresentableMessage" => "A webhook for the URL 'https://linear-sync.com/webhook/linear' already exists on the team."}, "locations" => [%{"column" => 3, "line" => 2}], "message" => "url not unique", "path" => ["webhookCreate"]}]}}
```

**Comment by seripap** [comment]
Yeah- was assuming hooks would be deleted/added on enable/disable. I did ran into a similar issue when implementing, hence the `get_webhooks` function. Can take a further look later when I have some free time.

**Comment by jtormey** [comment]
Two-way sync is now supported, and the webhooks design has been updated to support any number / combination of webhooks for both Linear and GitHub.

**Comment by jtormey** [comment]
Hi @folex! This should already work, as long as you have the option to sync Linear issues to GitHub enabled.

If you try it out and it doesn't work, feel free to open a new issue here 🙂
